events.listen('recipes', function (e) {
	
	e.shapeless('minecraft:oak_planks', ['minecraft:oak_slab', 'minecraft:oak_slab'])
	e.shapeless('minecraft:dark_oak_planks', ['minecraft:dark_oak_slab', 'minecraft:dark_oak_slab'])
	e.shapeless('minecraft:birch_planks', ['minecraft:birch_slab', 'minecraft:birch_slab'])
	e.shapeless('minecraft:acacia_planks', ['minecraft:acacia_slab', 'minecraft:acacia_slab'])
	e.shapeless('minecraft:spruce_planks', ['minecraft:spruce_slab', 'minecraft:spruce_slab'])
	e.shapeless('minecraft:jungle_planks', ['minecraft:jungle_slab', 'minecraft:jungle_slab'])
	e.shapeless('minecraft:cobblestone', ['minecraft:cobblestone_slab', 'minecraft:cobblestone_slab'])
	e.shapeless('minecraft:mossy_cobblestone', ['minecraft:mossy_cobblestone_slab', 'minecraft:mossy_cobblestone_slab'])
	e.shapeless('minecraft:stone', ['minecraft:stone_slab', 'minecraft:stone_slab'])
	e.shapeless('minecraft:smooth_stone', ['minecraft:smooth_stone_slab', 'minecraft:smooth_stone_slab'])
	e.shapeless('minecraft:sandstone', ['minecraft:sandstone_slab', 'minecraft:sandstone_slab'])
	e.shapeless('minecraft:smooth_sandstone', ['minecraft:smooth_sandstone_slab', 'minecraft:smooth_sandstone_slab'])
	e.shapeless('minecraft:cut_sandstone', ['minecraft:cut_sandstone_slab', 'minecraft:cut_sandstone_slab'])
	e.shapeless('minecraft:red_sandstone', ['minecraft:red_sandstone_slab', 'minecraft:red_sandstone_slab'])
	e.shapeless('minecraft:smooth_red_sandstone', ['minecraft:smooth_red_sandstone_slab', 'minecraft:smooth_red_sandstone_slab'])
	e.shapeless('minecraft:cut_red_sandstone', ['minecraft:cut_red_sandstone_slab', 'minecraft:cut_red_sandstone_slab'])
	e.shapeless('minecraft:bricks', ['minecraft:brick_slab', 'minecraft:brick_slab'])
	e.shapeless('minecraft:stone_bricks', ['minecraft:stone_brick_slab', 'minecraft:stone_brick_slab'])
	e.shapeless('minecraft:mossy_stone_bricks', ['minecraft:mossy_stone_brick_slab', 'minecraft:mossy_stone_brick_slab'])
	e.shapeless('minecraft:nether_bricks', ['minecraft:nether_brick_slab', 'minecraft:nether_brick_slab'])
	e.shapeless('minecraft:red_nether_bricks', ['minecraft:red_nether_brick_slab', 'minecraft:red_nether_brick_slab'])
	e.shapeless('minecraft:quartz_block', ['minecraft:quartz_slab', 'minecraft:quartz_slab'])
	e.shapeless('minecraft:smooth_quartz', ['minecraft:smooth_quartz_slab', 'minecraft:smooth_quartz_slab'])
	e.shapeless('minecraft:purpur_block', ['minecraft:purpur_slab', 'minecraft:purpur_slab'])
	e.shapeless('minecraft:prismarine', ['minecraft:prismarine_slab', 'minecraft:prismarine_slab'])
	e.shapeless('minecraft:prismarine_bricks', ['minecraft:prismarine_brick_slab', 'minecraft:prismarine_brick_slab'])
	e.shapeless('minecraft:dark_prismarine', ['minecraft:dark_prismarine_slab', 'minecraft:dark_prismarine_slab'])
	e.shapeless('minecraft:granite', ['minecraft:granite_slab', 'minecraft:granite_slab'])
	e.shapeless('minecraft:polished_granite', ['minecraft:polished_granite_slab', 'minecraft:polished_granite_slab'])
	e.shapeless('minecraft:diorite', ['minecraft:diorite_slab', 'minecraft:diorite_slab'])
	e.shapeless('minecraft:polished_diorite', ['minecraft:polished_diorite_slab', 'minecraft:polished_diorite_slab'])
	e.shapeless('minecraft:end_stone_bricks', ['minecraft:end_stone_brick_slab', 'minecraft:end_stone_brick_slab'])
	e.shapeless('minecraft:andesite', ['minecraft:andesite_slab', 'minecraft:andesite_slab'])
	e.shapeless('minecraft:polished_andesite', ['minecraft:polished_andesite_slab', 'minecraft:polished_andesite_slab'])
	
	e.shapeless('craftingstation:crafting_station',['craftingstation:crafting_station_slab', 'craftingstation:crafting_station_slab'])
	
	e.shapeless('mysticalagriculture:soulstone',['mysticalagriculture:soulstone_slab', 'mysticalagriculture:soulstone_slab'])
	e.shapeless('mysticalagriculture:soulstone_cobble',['mysticalagriculture:soulstone_cobble_slab', 'mysticalagriculture:soulstone_cobble_slab'])
	e.shapeless('mysticalagriculture:soulstone_bricks',['mysticalagriculture:soulstone_bricks_slab', 'mysticalagriculture:soulstone_bricks_slab'])
	e.shapeless('mysticalagriculture:soulstone_smooth',['mysticalagriculture:soulstone_smooth_slab', 'mysticalagriculture:soulstone_smooth_slab'])
	
})